### ISSUE TITLE
ui-kit

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#1]
Не увидел начальной страницы с элементами, той, которая должна получиться по макету. Скинь плиз путь на нее от localhost.../

**Comment by pasha-zolotukhin** [comment]
А я думал что там задание заключалось в том, чтобы показать как работают ui kit на сайте. Макет тоже нужен?

**Comment by Frolikow** [comment]
третий пункт
![image](https://user-images.githubusercontent.com/25764783/55872628-a791be00-5bb7-11e9-9724-183515734abd.png)

**Comment by pasha-zolotukhin** [comment]
А, блин, мой косяк.

**Comment by Frolikow** [comment]
когда сделаешь,  напишешь в телеграме, чтобы я проверял

**Comment by pasha-zolotukhin** [comment]
Хорошо.
