### ISSUE TITLE
деструктуризация параметров

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#11]
Например здесь, у тебя слово options 22раза на 17 строчках)
![image](https://user-images.githubusercontent.com/25764783/56180107-41cb8900-6032-11e9-92d2-492fcacbad77.png)
старайся всегда делать деструктуризацию, меньше дублирования будет и читаемость лучше.

**Comment by pasha-zolotukhin** [comment]
Это я как раз хотел [здесь](#10) сделать)

**Comment by Frolikow** [comment]
То ишью закрой и сюда комить) чтоб по названию было четко понятно что в этом ишью) 

а
>  [здесь](https://github.com/pasha-zolotukhin/ui-kit-project/issues/10) 

непонятно что ты имел ввиду говоря про "более чистый код". 


Или же там переименуй, добавь пример ошибки и описание, а это ишью закроем

**Comment by pasha-zolotukhin** [comment]
Ок, решил сюда коммитить.
