### ISSUE TITLE
стили слайдеров

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#12]
Не находит путь до файла стилей
![image](https://user-images.githubusercontent.com/25764783/56183072-01bed300-603f-11e9-926f-12bdf43c71aa.png)
Вручную, тоже файла не оказалось по указанному пути. 
Ты его не сам дописывал? 

Если ты будешь подключать свой плагин слайдера, и это удалится, то вопрос закроем. 
Когда(если) подключишь, то здесь укажи в коменте ссылку на то ишью, в котором подключил и можно будет закрыть это ишью

**Comment by pasha-zolotukhin** [comment]
#3
