### ISSUE TITLE
code style 

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#15]
В js при именовании придерживайся одного правила. Если у тебя camelCase, то следи чтобы он был везде
![image](https://user-images.githubusercontent.com/25764783/56361288-2ff40c80-6211-11e9-8380-8af4305fcda8.png)

**Comment by pasha-zolotukhin** [comment]
Если ты про нижнее подчеркивание, то это просто приватное свойство/метод
![Снимок](https://user-images.githubusercontent.com/26360624/56368973-ab11ee80-6222-11e9-94bf-da4295d7f4b1.PNG)

**Comment by Frolikow** [comment]
я про rangeslider. Такого слова нету, но есть range и есть slider. Поэтому правильно будет rangeSlider. И как я понял это касается всего твоего плагина(третий проект). Или есть какая-то причина почему именно так названо?

**Comment by pasha-zolotukhin** [comment]
Переименовал) В 3 проекте соответствующее ишью создал тоже.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/56372251-d7306e00-6228-11e9-9bee-4acc38db6e33.png)
еще не все) и обрати внимание, что если rangeslider относиться к классу элемента, то camelCase не подойдет уже надо через `-` писать: range-slider.

**Comment by pasha-zolotukhin** [comment]
Получается файлы тоже нужно переименовать как-то?

**Comment by Frolikow** [comment]
По хорошему - да) У тебя и readme четко прописано, что это два слова: 
![image](https://user-images.githubusercontent.com/25764783/56451267-1b209180-6355-11e9-9a31-4cbb4536afe1.png)
а вообще почему range-slider? почему не просто slider? можешь объяснить причину выбора именно такого имени?

**Comment by pasha-zolotukhin** [comment]
Потому что когда я искал плагин для jquery по запросу "slider", то в результате натыкался на слайдер с изображениями. А такую штуку как в этом проекте именуют "range slider")
