### ISSUE TITLE
Ошибки слайдеров

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#3]
1) на первом слайдере, если я возьмусь за тултип за самый левый или правый край, то ползунок не двигается до, соответственно, левого или правого края. оставляя примерно 3 пункта.
![image](https://user-images.githubusercontent.com/25764783/56079834-e035cf80-5e23-11e9-92a4-981f9d8b590e.png)

2) второй слайдер, должен быть дискретным. т.е.не только шкалу иметь но и перемещаться по этой шкале - шагами равными диапазону между двух соседних значений шкалы
такого быть не должно: 
![image](https://user-images.githubusercontent.com/25764783/56079815-a795f600-5e23-11e9-90b1-f692130087fc.png)

**Comment by pasha-zolotukhin** [comment]
А я могу свой слайдер заюзать? ))

**Comment by pasha-zolotukhin** [comment]
Могу ли я заюзать свой плагин из 3 проекта?

**Comment by pasha-zolotukhin** [comment]
Могу ли я заюзать свой плагин из 3 проекта?)

**Comment by Frolikow** [comment]
конечно) но не забудь стили сделать под макет
