### ISSUE TITLE
элемент поиска

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/ui-kit-project#4]
При каких условиях, в строке поиска можно получить такое состояние?
![image](https://user-images.githubusercontent.com/25764783/56079860-4cb0ce80-5e24-11e9-8eaa-a2c3e747e476.png)

**Comment by pasha-zolotukhin** [comment]
Нужно задать модификатор search_failed.

**Comment by Frolikow** [comment]
в таком случае на один из элементов добавь этот модификатор, чтоб отображалось как в макете
