### ISSUE TITLE
Наименование модификаторов

### ISSUE THREAD

**Issue by pasha-zolotukhin** [pasha-zolotukhin/ui-kit-project#9]
Переименовать модификаторы типа ключ-значение по БЭМу: имя-блока_имя-модификатора_значение-модификатора.

https://github.com/pasha-zolotukhin/ui-kit-project/blob/18b2471ce2b8f9a660069a5abd06b2847784a4bf/src/components/arrow-button/arrow-button.pug#L4-L5

https://github.com/pasha-zolotukhin/ui-kit-project/blob/18b2471ce2b8f9a660069a5abd06b2847784a4bf/src/components/arrow-button/arrow-button.pug#L8-L10

**Comment by Frolikow** [comment]
можешь закрывать
